earn-for-free: false
switch-type-permission-needed: true
allowed-switches:
  wood-plate: true
  stone-plate: true
  button: true
  lever: true
  detector-rail: true
vehicle-support: true
notify-owner: true
notify-owner-free: true
limits:
  price:
    default: 0
messages:
  use-noperm: '&4You don''t havepermission to use PaidSwitches!'
  use-free: '&aYou used PaidSwitch for free!'
  use-paid: '&aYou paid %s for activating the switch./n&aNow you have %s'
  use-need: '&4You need %s to activate the switch.'
  use-notify: '&a%1$s used your paid %2$s (%3$s) for %4$s'
  use-notify-free: 'free'
  create-noperm: '&4You don''t have permission to create PaidSwitch!'
  create-noperm-type: '&4You don''t have permission to create paid %s!'
  create-noswitch: '&4No switch found!'
  create-others: '&4You don''t have permission to create PaidSwitch for other players!'
  create-noaccount: '&4Account %s does not exist!'
  create-nobank: '&6Your economy doesn''t support banks.'
  create-noprice: '&4Invalid price: %s'
  create-exceeded-price: '&4You can create switches that cost at most %s'
  create-ok: '&aSuccesfully created PaidSwitch!'
  create-duplicate: '&4You don''t have permission to create a second sign for other player''s PaidSwitch!'
log-level: INFO