name: PaidSwitch
main: com.github.wolf480pl.PaidSwitch.PaidSwitch
version: 0.6.1
depend: [Vault]
commands:
    paidswitch:
        description: Info about PaidSwitch and config reload.
        aliases: [paidsw, psw]
        permission: paidswitch.admin
        usage: |
            PaidSwitch 0.6.1 by Wolf480pl (wolf480@interia.pl)
            Usage:
            /paidswitch reload - reload config.yml
            Aliases: /paidsw, /psw
permissions:
    paidswitch.*:
        description: Gives all PaidSwitch permissions excepting free use.
        children:
            paidswitch.use: true
            paidswitch.create: true
            paidswitch.create.others: true
            paidswitch.create.duplicate: true
            paidswitch.create.type.*: true
    paidswitch.use:
        description: Allows to use PaidSwitches.
        default: true
    paidswitch.use.free:
        description: Allows to use PaidSwitches for free.
        default: false
        children:
            paidswitch.use: true
    paidswitch.create:
        description: Allows to create PaidSwitches.
        default: op
    paidswitch.create.others:
        description: Allows to create PaidSwitches for someone else.
        default: op
    paidswitch.create.duplicate:
        description: Allows to create a second sign for other players' PaidSwitches.
        default: op
    paidswitch.create.type.*:
        description: Allows to crate all types of PaidSwitches.
        children:
            paidswitch.create.type.wood-plate: true
            paidswitch.create.type.stone-plate: true
            paidswitch.create.type.button: true
            paidswitch.create.type.lever: true
            paidswitch.create.type.detector-rail: true
    paidswitch.create.type.wood-plate:
        description: Allows to crate paid wood plate.
        default: op
    paidswitch.create.type.stone-plate:
        description: Allows to crate paid stone plate.
        default: op
    paidswitch.create.type.button:
        description: Allows to crate paid button.
        default: op
    paidswitch.create.type.lever:
        description: Allows to crate paid lever.
        default: op
    paidswitch.create.type.detector-rail:
        description: Allows to crate paid wood plate.
        default: op
    paidswitch.admin:
        description: Gives access to /paidswitch command.
        default: op